spring:
  application:
    name: spring-multi-threading
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true

management:
  observations:
    annotations:
      enabled: true